//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace SvalboardLayerViz.App.Resources;

/// <summary>
/// A strongly-typed resource class for looking up localized strings.
/// </summary>
public static class Strings
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager(
            "SvalboardLayerViz.App.Resources.Strings",
            typeof(Strings).Assembly);

    public static CultureInfo? Culture { get; set; }
}
