<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SvalboardLayerViz.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="SharpCompress" Version="0.37.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SvalboardLayerViz.Tests" />
  </ItemGroup>

</Project>
